### ISSUE TITLE
Automation with sandboxie

### ISSUE THREAD

**Issue by pisctarius** [gg/sandboxie-py#3]
i want to make an auto login with sandboxie . i can open app with this code but how to handle with this process on box to press key ? thank

**Comment by gg** [comment]
This is beyond the scope of this project.

These packages may help with your automation needs:
- [pywinauto](https://pywinauto.github.io/)
- [PyAutoGUI](https://pyautogui.readthedocs.io/en/latest/)

**Comment by javohirkamolov14** [comment]
ok
